### ISSUE TITLE
Port to GTK+ 3

### ISSUE THREAD

**Issue by quozl** [sugarlabs/analyze#7]
- [ ] fix #1; because porting a non-functional activity is impossible to test,
- [ ] port from GTK+ 2 to GTK+ 3, a guide is on the Wiki,
- [ ] port from deprecated HippoCanvaxBox,
- [ ] port from sugar to sugar3,
- [ ] port pyxres.py from CDDL of libXres.so and libXmu.so.6 to Python xcbgen, xcffib, or xpyb,

(_contributed comments have been merged and deleted, thanks_)

**Comment by walterbender** [comment]
HippoCanvasBox is deprecated.

**Comment by yashagrawal3** [comment]
I am not able to find any helpful source to guide me to port it to gtk+ 3, please provide me one!

**Comment by quozl** [comment]
I just do it, I don't use any helpful source.

**Comment by yashagrawal3** [comment]
I don't have much of experience in it. I need some help. :P

**Comment by quozl** [comment]
What have you tried so far?  Do you have the API documentation for GTK+ 2 and GTK+ 3?

**Comment by walterbender** [comment]
There is a guide in the wiki.

**Comment by quozl** [comment]
Given #9, closing this.
